# deployment/k8s/caddy-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-pvc
  namespace: app-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---